services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy
        restart: true
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "some_password"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s